version: '2'

services:
  reference-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: docker.artifactory.reform.hmcts.net/common-components/reference-api
    ports:
     - 8080:8080
