version: '2'

services:
  reference-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - auth.provider.service.client.baseUrl=http://service-auth-provider-api:8080/
      - auth.provider.service.client.microservice=reference
      - auth.provider.service.client.key=AAAAAAAAAAAAAAAA
      - auth.idam.client.baseUrl=http://idam-api:8080/
      - payment.client.baseUrl=http://payments-api:8080/
    ports:
     - 8080:8080
    links:
     - payments-api
     - service-auth-provider-api
     - idam-api
    depends_on:
     - payments-api
     - service-auth-provider-api
     - idam-api

  # payments
  payments-api:
    image: docker.artifactory.reform.hmcts.net/common-components/payments-api
    command: --wait-for-database 30
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payments-database:5432/payment
      - auth.provider.service.client.baseUrl=http://service-auth-provider-api:8080/
      - auth.idam.client.baseUrl=http://idam-api:8080/
      - gov.pay.auth.key.reference=7t9jk8qt31jntnqn8mut1ab7956eflukd82grjhshogc45node4h89m9e3
    ports:
     - 8081:8080
    links:
     - payments-database
     - service-auth-provider-api
     - idam-api
    depends_on:
     - payments-database
     - service-auth-provider-api
     - idam-api

  payments-database:
    image: docker.artifactory.reform.hmcts.net/common-components/payments-database
    ports:
      - 5431:5432

  # IDAM
  idam-api:
    image: docker.artifactory.reform.hmcts.net/auth/idam-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://idam-database:5432/idam
      - idam.testing-support.enabled=true
    ports:
      - 8084:8080
    links:
     - idam-database
    depends_on:
     - idam-database

  idam-database:
    image: docker.artifactory.reform.hmcts.net/auth/idam-database
    ports:
      - 5434:5432

  # service-auth-provider
  service-auth-provider-api:
    image: docker.artifactory.reform.hmcts.net/auth/service-auth-provider-api
    environment:
      - auth.provider.service.server.jwtKey=wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      - auth.provider.service.server.microserviceKeys.reference=AAAAAAAAAAAAAAAA
      - auth.provider.service.testing-support.enabled=true
    ports:
      - 8085:8080

